export const services = [
  {
    slug: "home-moving-jeddah",
    titleAr: "نقل منازل وشقق بجدة",
    titleEn: "Home and Apartment Moving in Jeddah",
    descAr: "خدمة نقل احترافية للمنازل والشقق بجدة مع فريق متخصص ومعدات حديثة",
    descEn: "Professional home and apartment moving service in Jeddah with specialized team and modern equipment",
    image: "/images/home movers Jeddah.jpg",
  },
  {
    slug: "villa-moving-jeddah",
    titleAr: "نقل فلل بجدة",
    titleEn: "Villa Moving in Jeddah",
    descAr: "نقل فلل كامل مع فك وتركيب وتغليف محترف لجميع محتويات الفيلا",
    descEn: "Complete villa moving with professional disassembly, packing and reassembly",
    image: "/images/villa movers Jeddah.jpg",
  },
  {
    slug: "office-relocation-jeddah",
    titleAr: "نقل مكاتب وشركات بجدة",
    titleEn: "Office Relocation in Jeddah",
    descAr: "نقل مكاتب احترافي مع تقليل التوقف وخطط مخصصة للشركات",
    descEn: "Professional office relocation with minimal downtime and customized corporate plans",
    image: "/images/office movers Jeddah.jpg",
  },
  {
    slug: "packing-unpacking",
    titleAr: "خدمات التغليف وفك التغليف",
    titleEn: "Packing and Unpacking Services",
    descAr: "تغليف احترافي بمواد عالية الجودة لحماية أثاثك أثناء النقل",
    descEn: "Professional packing with high-quality materials to protect your furniture during moving",
    image: "/images/packing services Jeddah.jpg",
  },
  {
    slug: "disassembly-reassembly",
    titleAr: "فك وتركيب الأثاث",
    titleEn: "Furniture Disassembly and Reassembly",
    descAr: "فك وتركيب احترافي لغرف النوم والأثاث المعقد مع ضمان كامل",
    descEn: "Professional disassembly and reassembly of bedrooms and complex furniture with full warranty",
    image: "/images/dismantling furniture Jeddah.jpg",
  },
  {
    slug: "ac-curtains-installation",
    titleAr: "فك وتركيب المكيفات والستائر",
    titleEn: "AC and Curtains Installation",
    descAr: "خدمة فك وتركيب المكيفات والستائر من قبل فنيين متخصصين",
    descEn: "AC and curtains installation and removal service by specialized technicians",
    image: "/images/professional movers Jeddah.jpg",
  },
  {
    slug: "appliances-tv-mounting",
    titleAr: "تركيب الأجهزة والتلفزيونات",
    titleEn: "Appliances and TV Mounting",
    descAr: "تركيب احترافي للأجهزة والتلفزيونات على الجدران بأمان",
    descEn: "Professional mounting of appliances and TVs on walls safely",
    image: "/images/professional packing and moving.jpg",
  },
  {
    slug: "hoist-crane-moving",
    titleAr: "الونش والرافعة للعفش الثقيل",
    titleEn: "Hoist and Crane Moving",
    descAr: "استخدام الونش والرافعات لنقل العفش الثقيل من والى الأدوار العالية",
    descEn: "Using hoists and cranes to move heavy furniture to and from high floors",
    image: "/images/heavy furniture movers.jpg",
  },
  {
    slug: "intra-building-moving",
    titleAr: "نقل داخلي داخل المبنى",
    titleEn: "Intra-Building Moving",
    descAr: "نقل العفش بين الطوابق داخل نفس المبنى أو البرج",
    descEn: "Moving furniture between floors within the same building or tower",
    image: "/images/apartment movers Jeddah.jpg",
  },
  {
    slug: "urgent-night-weekend",
    titleAr: "نقل عاجل وليلي وعطلات",
    titleEn: "Urgent, Night and Weekend Moving",
    descAr: "خدمة نقل متاحة على مدار الساعة للحالات العاجلة والنقل الليلي",
    descEn: "24/7 moving service available for urgent cases and night moving",
    image: "/images/door to door movers.jpg",
  },
  {
    slug: "long-distance-moving",
    titleAr: "نقل بين المدن",
    titleEn: "Long Distance Moving",
    descAr: "نقل العفش بين المدن السعودية بأمان وسرعة",
    descEn: "Safe and fast furniture moving between Saudi cities",
    image: "/images/moving trucks Jeddah.jpg",
  },
  {
    slug: "piano-heavy-items",
    titleAr: "نقل البيانو والأغراض الثقيلة",
    titleEn: "Piano and Heavy Items Moving",
    descAr: "نقل متخصص للبيانو والأغراض الثقيلة والحساسة",
    descEn: "Specialized moving for pianos and heavy, sensitive items",
    image: "/images/heavy furniture movers.jpg",
  },
  {
    slug: "fine-art-antiques",
    titleAr: "نقل التحف والأثاث الفاخر",
    titleEn: "Fine Art and Antiques Moving",
    descAr: "نقل آمن للتحف واللوحات والأثاث الفاخر مع تغليف خاص",
    descEn: "Safe moving of antiques, paintings and luxury furniture with special packing",
    image: "/images/fragile item movers.jpg",
  },
  {
    slug: "it-server-relocation",
    titleAr: "نقل غرف السيرفر والأجهزة الحساسة",
    titleEn: "IT and Server Room Relocation",
    descAr: "نقل احترافي لغرف السيرفر والأجهزة التقنية الحساسة",
    descEn: "Professional relocation of server rooms and sensitive technical equipment",
    image: "/images/office movers Jeddah.jpg",
  },
  {
    slug: "kitchen-disassembly",
    titleAr: "فك وتركيب المطابخ",
    titleEn: "Kitchen Disassembly and Installation",
    descAr: "فك وتركيب المطابخ بجميع أنواعها من قبل فنيين متخصصين",
    descEn: "Disassembly and installation of all types of kitchens by specialized technicians",
    image: "/images/professional movers Jeddah.jpg",
  },
  {
    slug: "materials-supply",
    titleAr: "توريد مواد التغليف",
    titleEn: "Packing Materials Supply",
    descAr: "توفير جميع مواد التغليف من كراتين وفقاعات ومواد حماية",
    descEn: "Providing all packing materials including boxes, bubble wrap and protective materials",
    image: "/images/safe packing Jeddah.jpg",
  },
  {
    slug: "storage",
    titleAr: "التخزين الآمن",
    titleEn: "Safe Storage",
    descAr: "مستودعات آمنة لتخزين العفش قصير وطويل المدى",
    descEn: "Safe warehouses for short and long-term furniture storage",
    image: "/images/storage services Jeddah.jpg",
  },
  {
    slug: "corporate-contracts",
    titleAr: "حلول الشركات والعقود",
    titleEn: "Corporate Solutions and Contracts",
    descAr: "حلول مخصصة للشركات مع عقود سنوية وأسعار تفضيلية",
    descEn: "Customized solutions for companies with annual contracts and preferential prices",
    image: "/images/professional movers Jeddah.jpg",
  },
];

