export const site = {
  brand: "شركة الأفضل",
  phone: "+966560586397",
  whatsapp: "https://wa.me/966560586397",
  address: {
    full: "طريق الامير متعب بن عبدالعزيز، الرحاب، جدة 23344، السعودية",
    streetAddress: "طريق الامير متعب بن عبدالعزيز، الرحاب",
    addressLocality: "جدة",
    postalCode: "23344",
    addressCountry: "SA",
  },
  hours: [
    { day: "Monday", opens: "00:00", closes: "23:59" },
    { day: "Tuesday", opens: "00:00", closes: "23:59" },
    { day: "Wednesday", opens: "00:00", closes: "23:59" },
    { day: "Thursday", opens: "00:00", closes: "23:59" },
    { day: "Friday", opens: "00:00", closes: "23:59" },
    { day: "Saturday", opens: "00:00", closes: "23:59" },
    { day: "Sunday", opens: "00:00", closes: "23:59" },
  ],
  areaServed: [
    "Jeddah",
    "Al Hamra",
    "Ash Shati",
    "Al Rawdah",
    "As Salama",
    "Al Naeem",
    "Al Murjan",
    "An Nahdah",
    "An Nuzha",
    "Az Zahraa",
    "Al Bawadi",
    "Ar Rabwa",
    "Al Safa",
    "Al Khalidiya",
    "Al Andalus",
    "Al Aziziyah",
    "Ar Riyhab",
    "Al Balad",
    "Ar Ruwais",
    "Ash Sharafiyah",
    "Bani Malik",
    "Al Woroud",
    "An Naseem",
    "Al Baghdadiyah Ash Sharqiyah",
    "Al Mohamadiyah",
    "Al Basateen",
    "Ath Tha'alaba",
    "As Sulaymaniyah",
    "Al Jamaa",
    "Obhur North",
    "Obhur South",
    "Al Hamdaniyah",
  ],
};

export const areas = [
  { slug: "al-hamra", nameAr: "الحمراء", nameEn: "Al Hamra" },
  { slug: "ash-shati", nameAr: "الشاطئ", nameEn: "Ash Shati" },
  { slug: "al-rawdah", nameAr: "الروضة", nameEn: "Al Rawdah" },
  { slug: "as-salama", nameAr: "السلامة", nameEn: "As Salama" },
  { slug: "al-naeem", nameAr: "النعيم", nameEn: "Al Naeem" },
  { slug: "al-murjan", nameAr: "المرجان", nameEn: "Al Murjan" },
  { slug: "an-nahdah", nameAr: "النهضة", nameEn: "An Nahdah" },
  { slug: "an-nuzha", nameAr: "النزهة", nameEn: "An Nuzha" },
  { slug: "az-zahraa", nameAr: "الزهراء", nameEn: "Az Zahraa" },
  { slug: "al-bawadi", nameAr: "البوادي", nameEn: "Al Bawadi" },
  { slug: "ar-rabwa", nameAr: "الربوة", nameEn: "Ar Rabwa" },
  { slug: "al-safa", nameAr: "الصفا", nameEn: "Al Safa" },
  { slug: "al-khalidiya", nameAr: "الخالدية", nameEn: "Al Khalidiya" },
  { slug: "al-andalus", nameAr: "الأندلس", nameEn: "Al Andalus" },
  { slug: "al-aziziyah", nameAr: "العزيزية", nameEn: "Al Aziziyah" },
  { slug: "ar-rihab", nameAr: "الرحاب", nameEn: "Ar Rihab" },
  { slug: "al-balad", nameAr: "البلد", nameEn: "Al Balad" },
  { slug: "ar-ruwais", nameAr: "الرويس", nameEn: "Ar Ruwais" },
  { slug: "ash-sharafiyah", nameAr: "الشرفية", nameEn: "Ash Sharafiyah" },
  { slug: "bani-malik", nameAr: "بني مالك", nameEn: "Bani Malik" },
  { slug: "al-woroud", nameAr: "الورود", nameEn: "Al Woroud" },
  { slug: "an-naseem", nameAr: "النسيم", nameEn: "An Naseem" },
  {
    slug: "al-baghdadiyah-ash-sharqiyah",
    nameAr: "البغدادية الشرقية",
    nameEn: "Al Baghdadiyah Ash Sharqiyah",
  },
  { slug: "al-mohamadiyah", nameAr: "المحمدية", nameEn: "Al Mohamadiyah" },
  { slug: "al-basateen", nameAr: "البساتين", nameEn: "Al Basateen" },
  { slug: "ath-tha'alaba", nameAr: "الثعالبة", nameEn: "Ath Tha'alaba" },
  { slug: "as-sulaymaniyah", nameAr: "السليمانية", nameEn: "As Sulaymaniyah" },
  { slug: "al-jamaa", nameAr: "الجامعة", nameEn: "Al Jamaa" },
  { slug: "obhur-north", nameAr: "أبحر الشمالية", nameEn: "Obhur North" },
  { slug: "obhur-south", nameAr: "أبحر الجنوبية", nameEn: "Obhur South" },
  { slug: "al-hamdaniyah", nameAr: "الحمدانية", nameEn: "Al Hamdaniyah" },
];

export const routes = [
  {
    slug: "jeddah-to-riyadh",
    from: "جدة",
    to: "الرياض",
    toEn: "Riyadh",
    distance: "950 كم",
    duration: "9-10 ساعات",
  },
  {
    slug: "jeddah-to-makkah",
    from: "جدة",
    to: "مكة المكرمة",
    toEn: "Makkah",
    distance: "80 كم",
    duration: "1-1.5 ساعة",
  },
  {
    slug: "jeddah-to-madinah",
    from: "جدة",
    to: "المدينة المنورة",
    toEn: "Madinah",
    distance: "420 كم",
    duration: "4-5 ساعات",
  },
  {
    slug: "jeddah-to-taif",
    from: "جدة",
    to: "الطائف",
    toEn: "Taif",
    distance: "170 كم",
    duration: "2-2.5 ساعة",
  },
  {
    slug: "jeddah-to-yanbu",
    from: "جدة",
    to: "ينبع",
    toEn: "Yanbu",
    distance: "320 كم",
    duration: "3-4 ساعات",
  },
  {
    slug: "jeddah-to-abha",
    from: "جدة",
    to: "أبها",
    toEn: "Abha",
    distance: "630 كم",
    duration: "7-8 ساعات",
  },
  {
    slug: "jeddah-to-jazan",
    from: "جدة",
    to: "جازان",
    toEn: "Jazan",
    distance: "710 كم",
    duration: "8-9 ساعات",
  },
  {
    slug: "jeddah-to-tabuk",
    from: "جدة",
    to: "تبوك",
    toEn: "Tabuk",
    distance: "1050 كم",
    duration: "10-11 ساعة",
  },
  {
    slug: "jeddah-to-buraidah",
    from: "جدة",
    to: "بريدة",
    toEn: "Buraidah",
    distance: "950 كم",
    duration: "9-10 ساعات",
  },
  {
    slug: "jeddah-to-hail",
    from: "جدة",
    to: "حائل",
    toEn: "Hail",
    distance: "820 كم",
    duration: "8-9 ساعات",
  },
];







